# Generated by Django 5.1.5 on 2025-03-27 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_image',
            field=models.ImageField(null=True, upload_to='video-images'),
        ),
    ]
