# Generated by Django 5.1.5 on 2025-02-27 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='genres',
            new_name='genre',
        ),
    ]
