# Generated by Django 5.1.5 on 2025-03-28 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0003_alter_video_video_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_image',
            field=models.ImageField(null=True, upload_to='video-images'),
        ),
    ]
