# Generated by Django 5.1.5 on 2025-06-28 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0008_video_video_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(max_length=150),
        ),
    ]
